server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:jorgesmacbookpro.jks
    key-store-password: jorgesmacbookpro

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pew-tech/pewtechdemo-config-server-repo.git
          username: svc-account-config-server-dev
          password: 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
          basedir: target/config

encrypt:
  keyStore:
    location: classpath:config-server.jks
    password: pt3d3m0-cs-s70r3
    alias: config-server-key
    secret: pt3d3m0-cs-s70r3

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

