server:
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:jorgesmacbookpro.jks
    key-store-password: '{cipher}AgC9G7CG1yKZdCqYZaDOO0Yqeb7DaTAM6hcua3VJNs17xx4j4iwFUmSzH6HKBKjulvbD4SI2YvzLJXH+Osf6yJ11Cbxdi0wU2bNCbqmo/NnQX7ceOuXlnX741p1iV7bWTPDNqJg41yqn89GTiku3IUt0f6ALyZ6wFxDg3JkuFOJfOeRh4CoyQCp1yKs77uVM+Z4tBHZn7vpmmzqGAQUrFE8V/glB2T7+UJXMWTVDKWU9gUEV0mGXfkUYWUF23F2u7U4tx5w+YRWbVKish1selY/UZWzDyrJsZhYiPLc1pZaxH+C03S1LFaLPSAQ3INtyGLkaz40ZuyagF1rVBJvahqVVFd0p8SStHrRaqklT2qvcVBldQ8dNk5rbAE4R6w3oLJfrQmuxoT0GFy+wcfWgTFiew0AFjCrhxygySpqPO2LMfwwxb/Weczv0T0bhcHm82b4MqtjDvJy7Glg9RnTsxb4FUdWTO4ig9UObla070Jf8CSvapIobCoLoQVBtaii8uCPGKYX28U5qwL2pMF2ag1wncbGpVgG47iE5Fr7PthNuGtYUOFf0nfgGt4SfnOizTt4ODAtKTwFuhdna457Dc9WLfKlW6RjVlp/tzUUwPRfLD/1f1OJWRxRY9nZcnkLcRVouiieWxn5Q2Kl3d5dX44OnRLGLTqcm2dIWK3QH4uJF6KmvHEV9NS0kIRpmXOQtfYlQYBml62P6Xx1huORUB76tj145kn174Wr2CoTl6WISLQ=='

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pew-tech/pewtechdemo-config-server-repo.git
          username: '{cipher}AgBjgyfeGdkYWnfD2p6nzvNqB5sVcxIEWE/r6BTLGDxyEdaRm2eGwh1j0/QzpL8C31s8mCgX7fWos4SrRUuainVw1DhsrVu/TopOuazb1iQc3Bhq5hfCXDW2oOv1suQduJD0D1OUB3HNwCx2TspDGV+MgbRquVkw43QSOA2k0l28E9aNG/Du+dzW24OjDyl/va3g6mZtYEkN2cFrsfxHydF86fWUx7oB+4csz/H3ulQ4ccnrk3xFVdy93Vh7q73EdLmd5A0iTS66/AoNtBeyvjGz9k06Dgp8fE+jaIsLdRsz/zyTGAyRME8a4AahTAzxLBHnBErmiCX+nBvLkWwm1dt5IaGlajH/BpJPhJFILBywvatwU0e0AMry/kgxyswk0UaeUBJwldCszqyH+bxTio7OQARvNrFudmOByY02ZzV2dWmFlbHUUjuMndM56lwtJUANmv+a0WWkMMkUjbTVeqgLVW/uo5H6zxmdGWzEEDZx2u656sUOxm2BaWEneTUlcvBca6uoG3PK8r1tCBgAZ1sDQp0bqwUiK9kmGk4qimTjzh0hh/lbprM387rWADnLYZseQqaKLclPTxZDkYSJPtYdotH7CZEUjwh25CQ3+yGz6g7J/3Mp2bbzuE8IY3xehUGQx1o9Gavj8N4nQ96e/9knD4VqNGMuMMxI4ueuG6umwYSdzQQw9gAEV+YExVTD9UQx48BKcqvKWxORCSXc8FzvxSwGCGXOBGmBMw8wzVDRnA=='
          password: '{cipher}AgCMtS05zcfA3iWcNKegQZe2GVwu1Cw0NMkdOUFn3zDDEzzwfoqGZsMlo+ot0wP9FwTAiVb7uftNsU1dmHNOWPElWr/6A1Tj3G0vuj8ixsIcaCcIdwFrZXdWqSB4xiHpy/gCDiCUWcvazbR1RayH21PpqFUy6QMddwINGKpBdDxXjrDhTGSriRHBH8YYjv16wd3zZUI2OcwJnzsXOHxEp42JAs9F3aiYUaZxBvAAKe+25vnevysxhUleqcRYhwfZe01cuV2H7w7UNU5fNRFTVKD1DsxdZ2Ozt4S2nD5pBJfmQBQHSuu9BBwVlKgQu7V4frPkR07zWFGsKn75nJnpFW84q03/mYDVMuMtfNjzJbwIHFoYlJu2YYPaWajLMhlZvskBhsyUAtjkFciSPXG31dq8dS9bwSj4An4VDEotJI9cGDo36uhD7M+gbFsDcdcpiIOKdeMwwppNSGAn7UHkYB0r1v/AsfX9FyLdOpHfL4Y6Am4J6a/WFFjlS+V1J3Gl1LxjPh8lkjxOhHPUS25KzpTcUp4o3VdXEuUXdHm1PG0sAb6x/lthttMARADOkJCJk2hi4MgkGgSTqUQ/oUb+oNmqDzoG9CYwT9d1RDff65xg++pll49e+Z4ZRJoCeQ7NxoeSqykUAqDewetF1UzQZc+qBBpuxjYbVoAxflB8nlPZJ/O8FZsFCmX8BBjt7b+IlDoJr2jOuCzjXTYnBKnrzMapvxucb2BaFgp9ZomAyVCcfY4okX4MF0SP7uycQCpmJKo='
          basedir: target/config

encrypt:
  keyStore:
    location: classpath:config-server.jks
    password: pt3d3m0-cs-s70r3
    alias: config-server-key
    secret: pt3d3m0-cs-s70r3

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

